name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./gradlew build
        cp /home/runner/work/forecastie/forecastie/app/build/outputs/apk/release/app-release-unsigned.apk /home/runner/work/forecastie/forecastie/forecastie.apk

    - name: Upload .apk
      uses: actions/upload-artifact@v1
      with:
        name: Forecastie
        path: forecastie.apk

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: forecastie.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
